name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets\asthetic.jpg
    - assets\bracelet.jpg
    - assets\diamonds.jpg
    - assets\girl shoes.jpg
    - assets\gold.jpg
    - assets\ladies chappals.jpg
    - assets\ladies dress.jpg
    - assets\lipstick.jpg
    - assets\look.jpg
    - assets\makeup set.jpg
    - assets\makeup.jpg
    - assets\mens watches.jpg
    - assets\mens wear.jpg
    - assets\nike.jpg
    - assets\perfume.jpg
    - assets\rich.jpg
    - assets\rings.jpg
    - assets\shirts.jpg
    - assets\wedding.jpg
    - assets\wired headphones.jpg
    - assets\women dress.jpg
    - assets\women shoes.jpg
    - assets\crocs.jpg
    - assets\nailpolish.jpg
    - assets\banner_3.jpeg
    - assets\banner_2.jpeg
    - assets\banner_1.jpeg
    - assets\outfits.jpg
    - assets\necklace.jpg
    - assets\wedding.jpg
    - assets\girls dresses.jpg
    - assets\stylish shoes.jpg
    - assets\puma shoes.jpg
    - assets\men shoes.jpg
    - assets\women's.png
    - assets\shoes.png
    - assets\jewelry_earing.png
    - assets\all.png
    - assets\men's.png
    - assets\beauty.png
    - assets\offer_banner.jpg
    - assets\diwali-festival-offers.jpg
    - assets\images.png
    - assets\current-month-offer.jpg